### ISSUE TITLE
Store variable images globally

### ISSUE THREAD

**Issue by MasonProtter** [HarrisonGrodin/Rewrite.jl#31]
In the examples we have:
```julia
julia> x, y = Variable.([:x, :y], Ref(TypeSet(Int)));

julia> normalize(@term(diff(sin(2*$x) - log($x+$y), $x)))
@term(2 * cos(2x) - 1 / (x + y))
```
It'd be nice if one could instead just declare that `x` and `y` are integers and then not have to worry about interpolating later.

**Comment by HarrisonGrodin** [comment]
Agreed. This is a window into the major design flaw that currently exists with image storage, where variable images are stored only on each specific instance in the term tree. This leads to a number of confusing behaviors, especially in the context of displaying:
```julia
julia> x1 = Variable(:x, TypeSet(Int));
       x2 = Variable(:x, TypeSet(String));

julia> @term $x2 ^ (x + $x1)
@term(x ^ (x + x))

julia> x1
@term(x)

julia> x2
@term(x)

julia> x1 == x2
false
```

Since each term should have exactly one interpretation of what image set a variable is in, this is something we should definitely have. In an upcoming iteration of `Term` storage, I'm hoping to have each object store a dictionary mapping variables (terms in general? see #35) to image sets.

As far as visual representation goes, it might be nice to use a `where` clause to indicate image sets (with easy copy-paste in mind) - for example, `@term(((a ^ 2) + b) where {a > 3, b ∈ Odd})`. It would be even better to include variable image in a local context and only show the `where` clause when it's not already implied (similarly to how Julia will show `A.B` as a type name until `B` is accessible in the local scope) - however, that might be getting beyond the scope of this issue.

**Comment by MasonProtter** [comment]
I don't have a good handle on how your term objects work, but perhaps one solution would be to have a central `dict` that stores mappings from variables to images and then whenever a new `term` is made, we can check the `dict` to see if there is already an image for each variable? Or is this what you were saying in your comment?
